// Tests for the sources params builders.
//
// The Python original (_web/params/sources.py + _web/sources/add.py)
// is the normative wire-shape source — every builder's output here
// must match what `wire.Marshal` would emit for the equivalent
// positional literal in Python. We assert the byte output below as
// golden strings; a reviewer hand-editing a builder must hand-edit
// the matching golden here in the same commit so the diff is
// traceable.
//
// We do NOT use the testdata/golden.json table that
// `notebooks_test.go` uses — T-P6-1 is the first sources ticket, so
// the testdata file does not yet carry sources builders. The
// expected bytes below were generated by hand-rolling
// `wire.Marshal(BuildListSources(...))` and
// `wire.Marshal(BuildAddSourceURL(...))` in a scratch binary and
// pasting the literal bytes here.
package params

import (
	"strings"
	"testing"
)

// TestBuildListSources_Bytes — the GET_NOTEBOOK shape used by the
// listing surface. The trailing `[None, 0]` and the nested template
// block at slot 2 are load-bearing; pinned verbatim.
func TestBuildListSources_Bytes(t *testing.T) {
	got, err := Encode(func() []any { return BuildListSources("nb-1") })
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	// Wire shape: ["nb-1", null, [2, null, null, [1, null×9, [1]]], null, 0]
	// Serialized: ["nb-1",null,[2,null,null,[1,null,null,null,null,null,null,null,null,null,[1]]],null,0]
	want := `["nb-1",null,[2,null,null,[1,null,null,null,null,null,null,null,null,null,[1]]],null,0]`
	if string(got) != want {
		t.Fatalf("BuildListSources bytes differ\n got: %s\nwant: %s", got, want)
	}
}

// TestBuildAddSourceURL_Bytes — the golden encode test pinned
// against Python's `add_url_source` literal. The shape is the
// nested wrapper (#1546 wire migration): a fresh template block at
// slot 2, with the URL riding at source-spec slot 2.
func TestBuildAddSourceURL_Bytes(t *testing.T) {
	got, err := Encode(func() []any { return BuildAddSourceURL("nb-1", "https://example.com") })
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	// Wire shape:
	// [
	//   [[null, null, ["https://example.com"], null, null, null, null, null, null, null, 1]],
	//   "nb-1",
	//   [2, null, null, [1, null×9, [1]]]
	// ]
	want := `[[[null,null,["https://example.com"],null,null,null,null,null,null,null,null,1]],"nb-1",[2,null,null,[1,null,null,null,null,null,null,null,null,null,[1]]]]`
	if string(got) != want {
		t.Fatalf("BuildAddSourceURL bytes differ\n got: %s\nwant: %s", got, want)
	}
}

// TestBuildAddSourceURL_GoldenExample — the pin from the ticket
// body. The exact bytes here are the contract; a reviewer changing
// the builder must change this string in the same commit so the
// diff is auditable.
func TestBuildAddSourceURL_GoldenExample(t *testing.T) {
	const want = `[[[null,null,["https://example.com/"],null,null,null,null,null,null,null,null,1]],"nb-1",[2,null,null,[1,null,null,null,null,null,null,null,null,null,[1]]]]`
	got, err := Encode(func() []any {
		return BuildAddSourceURL("nb-1", "https://example.com/")
	})
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	if string(got) != want {
		t.Fatalf("BuildAddSourceURL golden example mismatch\n got: %s\nwant: %s", got, want)
	}
}

// TestBuildListSources_NotebookIDRouted — slot 0 carries the
// notebook id verbatim; no rewriting.
func TestBuildListSources_NotebookIDRouted(t *testing.T) {
	got := BuildListSources("nb-abc-123")
	id, ok := got[0].(string)
	if !ok || id != "nb-abc-123" {
		t.Fatalf("BuildListSources slot 0 = %v, want \"nb-abc-123\"", got[0])
	}
}

// TestBuildListSources_Shape — five-slot shape with the trailing
// `[None, 0]` and the nested template block at slot 2.
func TestBuildListSources_Shape(t *testing.T) {
	got := BuildListSources("nb-1")
	if len(got) != 5 {
		t.Fatalf("BuildListSources len = %d, want 5", len(got))
	}
	if got[1] != nil {
		t.Errorf("BuildListSources slot 1 = %v, want nil", got[1])
	}
	if got[3] != nil {
		t.Errorf("BuildListSources slot 3 = %v, want nil", got[3])
	}
	// slot 4 is the trailing zero.
	if got[4] != 0 {
		t.Errorf("BuildListSources slot 4 = %v, want 0", got[4])
	}
	// slot 2 is the nested template block.
	if _, ok := got[2].([]any); !ok {
		t.Errorf("BuildListSources slot 2 type = %T, want []any", got[2])
	}
}

// TestBuildAddSourceURL_Shape — three-slot outer shape:
// [spec, notebook_id, template_block].
func TestBuildAddSourceURL_Shape(t *testing.T) {
	got := BuildAddSourceURL("nb-1", "https://example.com")
	if len(got) != 3 {
		t.Fatalf("BuildAddSourceURL len = %d, want 3", len(got))
	}
	if got[1] != "nb-1" {
		t.Errorf("BuildAddSourceURL slot 1 = %v, want \"nb-1\"", got[1])
	}
	// slot 0 is [[spec]] — double-wrapped.
	outer, ok := got[0].([]any)
	if !ok || len(outer) != 1 {
		t.Fatalf("BuildAddSourceURL slot 0 = %v, want [[spec]]", got[0])
	}
	spec, ok := outer[0].([]any)
	if !ok || len(spec) != 12 {
		t.Fatalf("BuildAddSourceURL spec len = %d, want 12", len(spec))
	}
	// spec slot 2 carries the [url] envelope.
	urlEnv, ok := spec[2].([]any)
	if !ok || len(urlEnv) != 1 || urlEnv[0] != "https://example.com" {
		t.Errorf("BuildAddSourceURL spec slot 2 = %v, want [\"https://example.com\"]", spec[2])
	}
	// spec slot 11 carries the trailing literal 1 (source-type code).
	if spec[11] != 1 {
		t.Errorf("BuildAddSourceURL spec slot 11 = %v, want 1", spec[11])
	}
}

// TestBuildAddSourceURL_TemplateBlockFresh — wire.TemplateBlock must
// return a fresh slice every call; the protocol parser rejects shared
// mutable nested literals. We mutate one returned slice and assert the
// next call is unaffected.
func TestBuildAddSourceURL_TemplateBlockFresh(t *testing.T) {
	a := BuildAddSourceURL("alpha", "https://a.example")
	a[2].([]any)[3].([]any)[0] = "MUTATED"
	b := BuildAddSourceURL("beta", "https://b.example")
	if b[2].([]any)[3].([]any)[0] != 1 {
		t.Fatalf("BuildAddSourceURL shared template block; got %v", b[2])
	}
}

// TestBuildAddSourceURL_URLAtSlot2 — the URL rides at source-spec
// slot 2 (the `_web/sources/add.py::add_url_source` literal). Pin
// it independently of the byte-exact golden above so a future shape
// change here is caught first by the descriptive test.
func TestBuildAddSourceURL_URLAtSlot2(t *testing.T) {
	got := BuildAddSourceURL("nb-1", "https://example.com")
	urlEnv, ok := got[0].([]any)[0].([]any)[2].([]any)
	if !ok {
		t.Fatalf("BuildAddSourceURL spec[2] not []any: %T", got[0].([]any)[0].([]any)[2])
	}
	if len(urlEnv) != 1 || urlEnv[0] != "https://example.com" {
		t.Errorf("BuildAddSourceURL spec[2] = %v, want [\"https://example.com\"]", urlEnv)
	}
}

// TestValidateURL_Accepts — the helper accepts a clean http / https
// URL and rejects every other shape (empty / whitespace / ftp /
// scheme-less).
func TestValidateURL_Accepts(t *testing.T) {
	cases := []string{
		"http://example.com",
		"https://example.com",
		"https://example.com/path?q=1&r=2#fragment",
		"https://example.com:8080/path",
	}
	for _, c := range cases {
		if err := ValidateURL(c); err != nil {
			t.Errorf("ValidateURL(%q) = %v, want nil", c, err)
		}
	}
}

// TestValidateURL_Rejects — the helper rejects empty / whitespace /
// non-http inputs.
func TestValidateURL_Rejects(t *testing.T) {
	cases := []string{
		"",
		"   ",
		"example.com",
		"ftp://example.com",
		"javascript:alert(1)",
		"//example.com",
		"https://example.com\n",
		"\thttps://example.com",
	}
	for _, c := range cases {
		if err := ValidateURL(c); err == nil {
			t.Errorf("ValidateURL(%q) returned nil err; want validation error", c)
		}
	}
}

// TestEncodeNoHTMLEscape — the byte output must not HTML-escape the
// `<`, `>`, or `&` characters (per AGENTS.md rule 3). Pin a builder
// that uses an URL containing these characters to assert the UTF-8
// round-trip.
func TestEncodeNoHTMLEscape_Sources(t *testing.T) {
	got, err := Encode(func() []any {
		return BuildAddSourceURL("nb-1", "https://example.com/?q=<&>")
	})
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	for _, esc := range []string{`\u003c`, `\u003e`, `\u0026`} {
		if strings.Contains(string(got), esc) {
			t.Errorf("Encode output contains HTML-escape sequence %s: %s", esc, got)
		}
	}
}

// TestBuilderCoverageCalls — exercises every Go builder directly so the
// coverage tool sees the function bodies.
func TestBuilderCoverageCalls_Sources(t *testing.T) {
	_ = BuildListSources("nb-1")
	_ = BuildAddSourceURL("nb-1", "https://example.com")
	if err := ValidateURL("https://example.com"); err != nil {
		t.Fatalf("ValidateURL accepted clean URL: %v", err)
	}
}
