// Package internal/cli — `notebooklm completion` subcommand.
//
// Shell completion scripts are generated by Cobra's standard
// generator (GenBashCompletion / GenZshCompletion / GenFishCompletion)
// and printed to stdout. The script is sourced into the user's
// shell to enable TAB completion; it is byte-clean and contains
// no escape sequences that conflict with the shell parser.
//
// The root command disables the auto-generated default
// (CompletionOptions.DisableDefaultCmd) so this subcommand is the
// single entry point. Calling `notebooklm completion bash` (or
// zsh / fish) prints the script for the requested shell.
//
// References:
//
//   - docs/07-cli-spec.md §"Cobra wiring notes" — completion
//     generators.
//   - github.com/spf13/cobra README — GenBashCompletion etc.
package cli

import (
	"github.com/spf13/cobra"
)

// newCompletionCmd returns the `completion` subcommand. The shell
// argument is a positional ValidArgs with the three documented
// values; passing anything else exits 2 with a usage error.
func newCompletionCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "completion {bash|zsh|fish}",
		Short: "Generate a shell-completion script",
		Long: `Print a shell-completion script for the requested shell.

To enable TAB completion for the current session:

  bash:  source <(notebooklm completion bash)
  zsh:   source <(notebooklm completion zsh)
  fish:  notebooklm completion fish | source

To enable completion in every new session, append the script to
your shell's rc file (e.g. ~/.bashrc, ~/.zshrc, ~/.config/fish/
config.fish) or to the system-wide completion directory.`,
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cobra.MatchAll(cobra.ExactArgs(1), cobra.OnlyValidArgs),
		ValidArgs:     []string{"bash", "zsh", "fish"},
		RunE: func(cmd *cobra.Command, args []string) error {
			shell := args[0]
			out := cmd.OutOrStdout()
			var err error
			switch shell {
			case "bash":
				err = cmd.Root().GenBashCompletion(out)
			case "zsh":
				err = cmd.Root().GenZshCompletion(out)
			case "fish":
				err = cmd.Root().GenFishCompletion(out, true)
			}
			return err
		},
	}
	// Disable the auto-generated "Completion" subcommand help
	// header (Cobra appends a line about `completion -h` if we do
	// not). The comment is for clarity — the default is fine.
	cmd.DisableAutoGenTag = true
	return cmd
}
